<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\UnityModManager\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>UnityModManager\%(RecursiveDir)%(FileName)%(Extension)</Link>
    </None>
    <None Update="Resources\UnityModManagerConfig.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>UnityModManagerConfig.xml</Link>
    </None>
    <None Include="Resources\Doorstop\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Doorstop\%(RecursiveDir)%(FileName)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>
